name: Dashboard UI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
  validate-locales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [check-license-lines, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
