name: Release Automation

on:
  push:
    branches: [main]

jobs:
  # Prepare entire repository release.
  release-please-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          last-release-sha: 722bd8394b7c16db960e12a40745e21a34027f07
          release-type: node
          package-name: polkadot-cloud

  # Note: Currently disabled due to API limits.

  # Dynamically fetches packages to publish from the `packages` folder. Uses `sed` to format the
  # list with quotes and commas. Wraps command output in angle brackets, resulting in a JSON
  # formatted string.
  # get-packages:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     packages: ${{ steps.get_packages.outputs.packages }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: "Get Packages"
  #       id: get_packages
  #       run: echo packages=[$(ls | sed 's,\(.*\),"\1"\,,')] >> "$GITHUB_OUTPUT"
  #       working-directory: "packages"

  # Note: Experimental and may not work as expected, and or be changed in future revisions.
  # Uses the above list of packages to prepare per-package releases.
  # release-please-packages:
  #   runs-on: ubuntu-latest
  #   needs: get-packages
  #   strategy:
  #     matrix:
  #       package: ${{ fromJson(needs.get-packages.outputs.packages) }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org

  #     - name: Release Please
  #       uses: google-github-actions/release-please-action@v3
  #       with:
  #         release-type: node
  #         package-name: ${{ matrix.package }}
  #         monorepo-tags: true
  #         command: github-release # Refer to https://github.com/marketplace/actions/release-please-action#configuration for configuring this field
  #         path: packages/${{ matrix.package }}
